#!/bin/bash



#
## generate the GeoIP ipv4/ipv6 block list for nftables.
# 



#
## the args ... example: ./genft it ru cn 
#
C_CODES="$@"
echo "[ ++ ] - Catching all ipv4 ipv6 from: $@"

# the dirs to store the coutry files
TMPDIR4=/tmp/countries4
TMPDIR6=/tmp/countries6
TMP_DIRS=( "${TMPDIR4}" "${TMPDIR6}" )

# Where is the script located? ... an output directory is to be created there.
OUTPUT=$( dirname  $( realpath "$0" ) )

# the output destinations for the final blocklists
OUTPUTv4="${OUTPUT}/output/ipv4.blocklist.nft"
OUTPUTv6="${OUTPUT}/output/ipv6.blocklist.nft"
OUT_FILES=( "${OUTPUTv4}" "${OUTPUTv6}" )


function gen_tables() {
    # generate the nft blocklists
    for Z_IP_F in $( /usr/bin/ls "${1}" ) ; do

        while read raw_ip ; do
            echo -e "    $raw_ip," >> "${2}"
        done < "${1}/$Z_IP_F"

    done  
}


#
## is the output dir existing? if not create it..
#
if [ ! -d "${OUTPUT}/output" ] ; then mkdir "${OUTPUT}/output" 2> /dev/null ; fi


for TMP_DIR in ${TMP_DIRS[@]} ; do 
    # create the tmp dirs and if they exists, delete its content
    if [ ! -d "${TMP_DIR}" ] ; then 
        mkdir -p "${TMP_DIR}"
    else
        echo "[ !! ] - Deleting Content of: $TMP_DIR"
        for C in $( /usr/bin/ls "${TMP_DIR}" ) ; do
            rm -f "${TMP_DIR}/$C" 2> /dev/null
        done
    fi
done


for C in ${C_CODES[@]} ; do
    # download all the ipv4 and ipv6 coutry files
    /usr/bin/curl -s -L -o "${TMPDIR4}/$C.ipv4.zone" "https://www.ipdeny.com/ipblocks/data/aggregated/$C-aggregated.zone"
    /usr/bin/curl -s -L -o "${TMPDIR6}/$C.ipv6.zone" "https://www.ipdeny.com/ipv6/ipaddresses/blocks/$C.zone"
done


for OUT_FILE in ${OUT_FILES[@]} ; do
    # erase the content of the old blocklists
    if [ -f "${OUT_FILE}" ] ; then
        echo "[ !! ] - Erase content of: ${OUT_FILE}" 
        echo '' > "${OUT_FILE}"
    fi
done


# write the default start into the nftables blocklist files
cat > "${OUTPUTv4}" << EOF
#!/usr/sbin/nft -f

define Blocklistv4 = {
EOF


cat > "${OUTPUTv6}" << EOF
#!/usr/sbin/nft -f

define Blocklistv6 = {
EOF

# write ipv4 and ipv6 addresses into the nftables blocklist files
gen_tables "${TMPDIR4}" "${OUTPUTv4}"
gen_tables "${TMPDIR6}" "${OUTPUTv6}"



for OUT_FILE in ${OUT_FILES[@]} ; do
    # add the } and we are fine
    echo -e "}" >> "${OUT_FILE}"
done



